### ISSUE TITLE
Reload is not available with electron

### ISSUE THREAD

**Issue by bokzor** [colinskow/angular-electron-dream-starter#14]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[x ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Is it possible to reload the application when a refresh is executed during the launch ?

* **What is the current behavior?**
For the moment after a refresh the application is not longer availaible (blanck page).
I suppose It's because webpack is injecting the scripts in a specific way...

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
The application should reload and hit the route 'home /'

* **What is the motivation / use case for changing the behavior?**
Better dev environment.

* **Please tell us about your environment:**

- Angular version: 4.x
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by okonon** [comment]
@colinskow  I am seeing same thing as @bokzor could you point us in right direction? Thanks a lot

**Comment by okonon** [comment]
Actually never mind started to work for me :)

**Comment by colinskow** [comment]
I've noticed this too. Sometimes the app loads blank. This is caused by a race condition between the main and renderer Webpack builds on the dev server. If the renderer process build is not finished when Electron starts it generates an error. The only solution I've found is to refresh manually by hitting CTRL-R. This should never happen with your production builds.

**Comment by colinskow** [comment]
I checked my code and it appears I fixed this a while back by forcing the main build to finish before the renderer build starts. If you can reproduce this with the latest version of the repo, feel free to re-open.

**Comment by mrmashal** [comment]
@colinskow Could you please tell me where was the fix? I have replaced some theme for the `src/app` (along with some required adjustments) and I'm facing the blank screen on page reload. I'm not sure if I've accidentally overwritten some important code. The theme does not use ngrx; Could it be related to the issue?
