### ISSUE TITLE
False positive e2e tests.

### ISSUE THREAD

**Issue by readme42** [colinskow/angular-electron-dream-starter#15]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
false positive e2e test results

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

See this fork. I modified the test, but when I build and test, all tests are green.
https://github.com/readme42/angular-electron-dream-starter/tree/bugfix/brokenEnd2EndTests

* **What is the expected behavior?**
Tests are failing

**Comment by readme42** [comment]
Upgrading chai-as-promised to v7.1.x seems to solve this.

**Comment by colinskow** [comment]
Okay, I have upgraded in the main repo. Feel free to re-open if not solved.
