### ISSUE TITLE
Cannot invoke an expression whose type lacks a call signature

### ISSUE THREAD

**Issue by celestale** [colinskow/angular-electron-dream-starter#18]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

> at-loader error found when running npm start

```
[at-loader] ./src/app/reducers/index.ts:36:12
    TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{}' has no compatible call signatures.
```

index.ts
```
const DEV_REDUCERS = [stateSetter, storeFreeze, storeLogger()];
**const developmentReducer = compose(...DEV_REDUCERS, combineReducers)(reducers);**
const productionReducer = compose(combineReducers)(reducers);

export function rootReducer(state: any, action: any) {
  if (ENV !== 'development') {
    return productionReducer(state, action);
  } else {
    **return developmentReducer(state, action);**
  }
}
```

**Comment by colinskow** [comment]
Downgrade to TypeScript 2.3.x.

**Comment by colinskow** [comment]
I was able to reproduce this when I upgraded to TypeScript 2.5.2. Fix incoming.
