### ISSUE TITLE
Unable to change packed filename executable 

### ISSUE THREAD

**Issue by celestale** [colinskow/angular-electron-dream-starter#19]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ * ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
A Question

* **What is the current behavior?**
Changing package.json `version `from 7.0.0 to 8.0.0 did not change the name of the packages,
Angular Electron Dream Starter Setup 7.0.0.exe to Angular Electron Dream Starter Setup 8.0.0.exe.

I ran `build:prod `and `package:windows`

* **What is the expected behavior?**
Packed filename: Angular Electron Dream Starter Setup 8.0.0.exe

Current environment: I just downloaded the latest source code with no changes expect the above.

**Comment by celestale** [comment]
Any help on this please? >.<

**Comment by colinskow** [comment]
This is handled through `electron-builder` a simple Google search will find the answer. Change the `productName` field in your `package.json`.
https://www.electron.build/configuration/configuration
