### ISSUE TITLE
The dist/package.json file is missing

### ISSUE THREAD

**Issue by chrisvelevitch** [colinskow/angular-electron-dream-starter#26]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **What is the current behavior?**
The packager is complaining that the dist/package.json is missing. What is meant to be in this file and shouldn't it be including in the repo?

* **What is the expected behavior?**
The app is packaged

* **What is the motivation / use case for changing the behavior?**
To have the package built

* **Please tell us about your environment:**

- Angular version: 4.4.4
- Browser: [Electron 1.7.9 Mac OS X 10.11.6 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run package:mac --scripts-prepend-node-path=auto

> angular-electron-dream-starter@7.0.0 package:mac /projects/angular-electron-dream-starter
> rimraf packages/mac/* && build --macos --x64

electron-builder 19.36.0
Error: Cannot find package.json in the /projects/angular-electron-dream-starter/dist
    at /projects/angular-electron-dream-starter/node_modules/electron-builder/src/packager.ts:207:11
```

**Comment by colinskow** [comment]
Did you do `npm run build:aot` first? I have tested recently on Mac and it is packaging correctly from my AoT build.

**Comment by chrisvelevitch** [comment]
Sorry, I overlooked that part of the process. It's working for me now.
