### ISSUE TITLE
Cannot find type definition file for 'electron'

### ISSUE THREAD

**Issue by samjegal** [colinskow/angular-electron-dream-starter#3]
Windows 10, already electron-rebuild procedure but I'v got error that 'Cannot find type definition file for electron',

E:\ElectronDev\angular-electron-dream-starter (master) (angular-electron-dream-starter@6.1.0)
λ yarn run build:dev
yarn run v0.24.5
$ npm run clean:build && npm run prep:dist && npm-run-all -p build:main:dev build:renderer:dev

> angular-electron-dream-starter@6.1.0 clean:build E:\ElectronDev\angular-electron-dream-starter
> rimraf dist dev compiled *.temp.json

> angular-electron-dream-starter@6.1.0 prep:dist E:\ElectronDev\angular-electron-dream-starter
> ncp node_modules_electron dist && rimraf dist/yarn.lock

yarn run v0.24.5
yarn run v0.24.5
$ webpack --config config/webpack.electron.js --progress --profile $ webpack --config config/webpack.dev.js --progress --profile

DLL: Checking if DLLs are valid.
DLL: All DLLs are valid.
  0% compiling 10% building modules 0/1 modules 1 active ...ream-starter\src\polyfi 10% building modules 0/1 modules 1 active ...on-dream-starter\src\main.electron.ts
[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from E:\ElectronDev\angular-electron-dream-starter\tsconfig.main.temp.json.
                                                                           10% building modules 0/2 modules 2 active ...ron-dream-starter\src\main.browser.ts[at-loader] Using typescript@2.3.4 from typescript and "tsconfig.json" from E:\ElectronDev\angular-electron-dream-starter\tsconfig.build.temp.json.
                                                                          708ms building modules
2ms sealing
0ms optimizing
1ms basic module optimization
0ms module optimization
1ms advanced module optimization
0ms basic chunk optimization
0ms chunk optimization
1ms advanced chunk optimization
0ms module and chunk tree optimization
1ms module reviving
0ms module order optimization
1ms module id optimization
1ms chunk reviving
0ms chunk order optimization
1ms chunk id optimization
3ms hashing
1ms module assets processing
4ms chunk assets processing
0ms additional chunk assets processing
1ms recording
0ms additional asset processing
8ms chunk asset optimization
 94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors                                                                                           307ms asset optimization
14ms emitting
Hash: 8a3b499b508c1b69e91c
Version: webpack 2.6.1
Time: 1078ms
       Asset     Size  Chunks             Chunk Names
    index.js  7.89 kB       0  [emitted]  index
index.js.map  7.81 kB       0  [emitted]  index
   [1] ./src/electron/index.ts 2.22 kB {0} [built]
       [] -> factory:10ms building:62ms = 72ms
   [2] ./src/electron/dev-extensions.ts 808 bytes {0} [built]
       [] -> factory:7ms building:26ms dependencies:0ms = 33ms
   [3] ./src/main.electron.ts 57 bytes {0} [built]
        factory:15ms building:602ms = 617ms
    + 5 hidden modules

ERROR in [at-loader] TS2688: Cannot find type definition file for 'electron'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:main:dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

E:\ElectronDev\angular-electron-dream-starter (master) (angular-electron-dream-starter@6.1.0)
λ

**Comment by samjegal** [comment]
I've modified below that remove electron section. Curiously enough good working build:dev option.
file: tsconfig.webpack.json
`"types": [
      "hammerjs",
      "node"
    ]`

**Comment by colinskow** [comment]
Sorry about that, I upgraded to Electron 1.72 which contains its own type files. I didn't remove all references completely to the old types. Thanks for pointing that out. Pushing fix now.
