### ISSUE TITLE
Packaging for linux cannot fetch appimage-9.0.1

### ISSUE THREAD

**Issue by m00s** [colinskow/angular-electron-dream-starter#30]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When running `npm run package:linux` I get this:

```
Packaging for linux x64 using electron 1.7.9 to packages/linux-unpacked
Building AppImage for arch x64
Building Snap for arch x64
Unable to find image 'electronuserland/builder:latest' locally
Downloading appimage-9.0.1, please wait
docker: Error response from daemon: Get https://registry-1.docker.io/v2/electronuserland/builder/manifests/latest: unauthorized: incorrect username or password.
See 'docker run --help'.
Error: docker exited with code 125
at ...
```

* **Please tell us about your environment:**
Building on macOS High Sierra 10.13.1

**Comment by colinskow** [comment]
This bug should be filed with `electron-builder ` instead. Generally building for a different OS than you are running is difficult. You may try installing a Linux VirtualBox to build instead.

**Comment by m00s** [comment]
@colinskow sounds good, thanks. For anyone having this issue I just login in docker cli using my username instead of the email.
