### ISSUE TITLE
Compatibility with use of browser

### ISSUE THREAD

**Issue by krisvantof** [colinskow/angular-electron-dream-starter#35]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Well... There is a Dockerfile for web browsing the `dist/` folder with Nginx, so I guess this is a bug. If it was never planned to be used with a browser, then it's a feature request, or a need for advice about what to do to get it.

* **What is the current behavior?**
Using this project with normal web browsing produces a blank page and an error in the browser console: missing "require" dependency.
```
ReferenceError: require is not defined [Learn More]
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
yarn install
yarn build
docker build -t dream-starter:latest .
docker run -p 80:80 dream-starter:latest
```
Open a browser at http://localhost

* **What is the expected behavior?**
I am sure that the popup window with ipc won't work. But it would be cool if the non-native features could work also in a browser, or to have at least the layout of the application.

* **What is the motivation / use case for changing the behavior?**
My use case is to share my application with others while it is in development, via the web, to get its global picture.

* **Please tell us about your environment:**
Ubuntu, Firefox, yarn

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I am a beginner with Electron and Webpack. I guess this issue has something to do with Webpack. Would it be possible to fix this just by adding a webpack configuration for web-browsing?

**Comment by colinskow** [comment]
Browser support is not a goal of this repo. Electron and browser builds can share a good deal of code, but you really need two separate build systems and two versions of the code for browser support.
