### ISSUE TITLE
Update to NGRX 4

### ISSUE THREAD

**Issue by Kaffiend** [colinskow/angular-electron-dream-starter#6]
Do you have plans to update to NGRX `4.x.x`?

**Comment by colinskow** [comment]
Absolutely. Pull requests welcome. Otherwise I'll probably get to it within the 2-3 couple weeks.

**Comment by Kaffiend** [comment]
I'd wait till the redux dev tools and router-store stop hating each other anyway 😺

**Comment by Kaffiend** [comment]
Given the simple nature of the starter, there is not enough to fully flex the new features of `NGRX 4.x`. Do you want to keep it simple as or add another module to explain the demo the async state and effects?

**Comment by Kaffiend** [comment]
also waiting for an update for HMR from angular class [here](https://github.com/AngularClass/angular-hmr/issues/59)

**Comment by Kaffiend** [comment]
@colinskow Forking a little more advanced version of this seed. NGRX 4 and all its features from the example app with this build pipeline is the target I'm aiming for. Took a bit and wrapped my head around the HMR aspect and i think i know where the issues lie.

**Comment by Kaffiend** [comment]
I've got it updated and working in my work project. I can issue a PR later this weekend for updating this seed and the slightly more advanced ngrx example app fork im working on.

**Comment by colinskow** [comment]
OK, I definitely want to get this seed working with NGRX 4. But it cannot break HMR. I'm open to a better example app, but don't want to make it too complicated. This is simply scaffolding for users to start their own apps.

**Comment by Kaffiend** [comment]
I've got the HMR working as well. I wont alter the seed example just update NGRX and its new API. I'm going to fork this seed with a merged `NGRX Official` example and if you like you can link to it in the ReadMe or something for anyone interested.
